"""empty message

Revision ID: 460137bc171a
Revises: c7dec52cb412
Create Date: 2020-05-05 05:20:37.485106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460137bc171a'
down_revision = 'c7dec52cb412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_description_key', 'product', type_='unique')
    op.drop_constraint('product_name_key', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_name_key', 'product', ['name'])
    op.create_unique_constraint('product_description_key', 'product', ['description'])
    # ### end Alembic commands ###
